# Generated by Django 6.0.2 on 2026-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('wallet', 'Wallet'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
